Repository q-optimize/c3, pull requests merged in 2021-03, with the labels that each got.

#65 Deprecation decorator and minor code cleanups
  c3/generator/devices.py
  c3/libraries/envelopes.py
  c3/utils/utils.py
Labels: code-quality, enhancement

#68 Bump qiskit to 0.23.6
  examples/c3_qiskit.ipynb
  requirements.txt
Labels: dependencies

#69 Hotfix: release pipeline
  .github/workflows/nightly_pypi.yml
  .github/workflows/publish_pypi.yml
Labels: bug

#63 Mutual inductance
  README.md
  c3/generator/devices.py
  c3/generator/generator.py
  c3/parametermap.py
  docs/optim_X.png
  test/conftest.py
  test/test_crosstalk.py
  test/test_generator.py
Labels: enhancement

#72 bump tensorflow to 2.4.1
  .pre-commit-config.yaml
  README.md
  requirements.txt
  setup.py
Labels: dependencies

#57 parametric gates
  .github/workflows/build_package.yml
  .github/workflows/coverage.yml
  .github/workflows/integration_test.yml
  c3/experiment.py
  c3/libraries/constants.py
  c3/libraries/fidelities.py
  c3/optimizers/c1.py
  c3/optimizers/c3.py
  c3/optimizers/optimizer.py
  c3/optimizers/sensitivity.py
  c3/parametermap.py
  c3/qiskit/c3_backend.py
  c3/qiskit/c3_backend_utils.py
  c3/signal/gates.py
  c3/system/model.py
  c3/utils/qt_utils.py
  c3/utils/tf_utils.py
  docs/Simulated_calibration.rst
  docs/c3_qiskit_example.rst
  docs/c3_qiskit_files/c3_qiskit_16_0.png
  docs/c3_qiskit_files/c3_qiskit_16_0.svg
  docs/c3_qiskit_files/c3_qiskit_18_0.png
  docs/c3_qiskit_files/c3_qiskit_18_0.svg
  docs/optimal_control.rst
  docs/two_qubits.rst
  examples/Simulated_calibration.ipynb
  examples/c3_qiskit.ipynb
  examples/quickstart.hjson
  examples/single_qubit_blackbox_exp.py
  examples/two_qubits.ipynb
  test/conftest.py
  test/instructions.cfg
  test/quickstart.hjson
  test/test_average_fidelity.py
  test/test_fidelities.py
  test/test_generator.py
  test/test_noise.py
  test/test_openqasm.py
  test/test_parameter_map.py
  test/test_parsers.py
  test/test_qiskit.py
  test/test_quick_setup.py
  test/test_tunable_coupler.py
  test/test_two_qubits.py
Labels: enhancement

#76 bump qiskit to 0.24.0
  requirements.txt
Labels: dependencies
