Repository q-optimize/c3, pull requests merged in 2021-01, with the labels that each got.

#10 Three wave mixing element, third order nonlinear hamiltonian and tests
  c3/libraries/hamiltonians.py
  c3/system/chip.py
  test/test_three_wave_mixer.py
Labels: enhancement, on-hold

#12 Support for running OpenQasm experiments with Qiskit
  .github/workflows/build_package.yml
  .gitignore
  c3/qiskit/__init__.py
  c3/qiskit/c3_backend.py
  c3/qiskit/c3_backend_utils.py
  c3/qiskit/c3_exceptions.py
  c3/qiskit/c3_job.py
  c3/qiskit/c3_provider.py
  c3/utils/tf_utils.py
  docs/c3_qiskit.rst
  docs/c3_qiskit_files/c3_qiskit_16_0.png
  docs/c3_qiskit_files/c3_qiskit_16_0.svg
  docs/index.rst
  examples/c3_qiskit.ipynb
  examples/generator.cfg
  examples/instructions.cfg
  examples/quickstart.hjson
  examples/test_model.cfg
  pytest.ini
  requirements.txt
  test/conftest.py
  test/test_qiskit.py
Labels: enhancement

#13 Tunable coupler elements and other significant additions
  c3/experiment.py
  c3/generator/devices.py
  c3/generator/generator.py
  c3/libraries/algorithms.py
  c3/libraries/envelopes.py
  c3/libraries/fidelities.py
  c3/optimizers/c1.py
  c3/optimizers/c1_robust.py
  c3/optimizers/c3.py
  c3/optimizers/optimizer.py
  c3/parametermap.py
  c3/signal/pulse.py
  c3/system/chip.py
  c3/system/model.py
  c3/system/tasks.py
  c3/utils/parsers.py
  c3/utils/qt_utils.py
  c3/utils/tf_utils.py
  c3/utils/utils.py
  docs/Simulated_calibration.rst
  examples/Simulated_calibration.ipynb
  examples/blackbox_exp.py
  examples/single_qubit_blackbox_exp.py
  pytest.ini
  test/generator.cfg
  test/test_generator.py
  test/test_tunable_coupler.py
  test/test_two_qubits.py
  test/tunable_coupler_data.pickle
  test/two_qubit_data.pickle
Labels: enhancement, on-hold

#23 Qiskit hotfix for iswap_optmap
  docs/c3.qiskit.rst
  docs/c3.rst
  docs/c3_qiskit_example.rst
  docs/c3_qiskit_files/c3_qiskit_16_0.png
  docs/c3_qiskit_files/c3_qiskit_16_0.svg
  docs/index.rst
  examples/c3_qiskit.ipynb
  examples/generator.cfg
  test/conftest.py
  test/generator.cfg
Labels: bug

#24 Add tests for Noise devices and Envelopes
  c3/experiment.py
  c3/generator/devices.py
  c3/libraries/envelopes.py
  c3/optimizers/c1.py
  c3/optimizers/c1_robust.py
  c3/optimizers/optimizer.py
  c3/utils/utils.py
  test/c1_robust.pickle
  test/test_envelope.py
  test/test_noise.py
  test/test_tunable_coupler.py
Labels: enhancement

#31 Contribution Guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#32 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
