Repository q-optimize/c3, pull requests merged in 2021-06, with the labels that each got.

#110 Add Introduction to Documentation
  docs/index.rst
  docs/intro.rst
Labels: documentation

#103 Fixed processing of model config file.
  README.md
  c3/model.py
  test/c1.cfg
  test/one_qubit.hjson
  test/test_model_breaking.cfg
  test/test_parsers.py
Labels: bug

#113 Bump tf version to fix vulnerabilities
  .pre-commit-config.yaml
  requirements.txt
  setup.py
Labels: dependencies, size/XS, tensorflow

#112 Add unit tests for qt_utils
  test/conftest.py
  test/test_qt_utils.py
Labels: code-quality, size/L

#116 Read and write a model's tasks to config files
  c3/libraries/tasks.py
  c3/model.py
  test/test_model_spam.cfg
  test/test_parsers.py
Labels: size/L
