Repository q-optimize/c3, pull requests merged in 2021-07, with the labels that each got.

#119 Integration Test for C2 style Calibration tasks
  c3/optimizers/c2.py
  test/c2.cfg
  test/test_c2_calibration.py
Labels: code-quality, size/L

#95 Make dependencies less strict
  requirements.txt
  setup.py
  test/test_envelopes.py
Labels: size/L

#123 Provide support for Python 3.9
  .github/workflows/build_package.yml
  .github/workflows/integration_test.yml
  .github/workflows/nightly_pypi.yml
  .github/workflows/publish_pypi.yml
  CONTRIBUTING.md
  setup.py
Labels: size/S

#124 Cleanup Algorithms Library
  c3/libraries/algorithms.py
  test/test_scan_algos.py
  test/test_two_qubits.py
Labels: code-quality, size/L

#120 Rename optimization procedures
  .gitignore
  c3/main.py
  c3/optimizers/calibration.py
  c3/optimizers/modellearning.py
  c3/optimizers/optimalcontrol.py
  c3/optimizers/optimalcontrol_robust.py
  c3/optimizers/sensitivity.py
  docs/Simulated_Model_Learning.rst
  docs/Simulated_calibration.rst
  docs/c3.optimizers.rst
  docs/optimal_control.rst
  examples/Simulated_Model_Learning.ipynb
  examples/Simulated_calibration.ipynb
  examples/two_qubits.ipynb
  test/test_c2_calibration.py
  test/test_model_learning.py
  test/test_noise.py
  test/test_optim_init.py
  test/test_qt_utils.py
  test/test_two_qubits.py
Labels: API-change, size/M

#125 Being Sensitive
  c3/libraries/algorithms.py
  c3/optimizers/modellearning.py
  c3/optimizers/sensitivity.py
  c3/utils/utils.py
  docs/Simulated_Model_Learning.rst
  docs/Simulated_Model_Learning_files/Simulated_Model_Learning_89_1.png
  docs/Simulated_Model_Learning_files/Simulated_Model_Learning_95_1.png
  docs/Simulated_calibration.rst
  examples/Simulated_Model_Learning.ipynb
  examples/Simulated_calibration.ipynb
  test/sensitivity.cfg
  test/test_optim_init.py
  test/test_sensitivity.py
Labels: bug, enhancement, size/XL

#126 Add a Changelog
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: code-quality, size/L

#128 Qiskit serialise
  CHANGELOG.md
  c3/qiskit/c3_backend.py
  test/test_qiskit.py
Labels: bug, size/XS
