Repository q-optimize/c3, pull requests merged in 2021-12, with the labels that each got.

#156 Drop support for Python 3.6
  .github/workflows/build_package.yml
  .github/workflows/nightly_pypi.yml
  .github/workflows/publish_pypi.yml
  CHANGELOG.md
  CONTRIBUTING.md
  setup.py
Labels: size/S

#154 Add an example notebook for two-qubit entangling gates
  CHANGELOG.md
  examples/Simulated_Model_Learning.ipynb
  examples/two_qubit_entangling_gate.ipynb
Labels: size/XXL

#158 Small fixes
  c3/c3objs.py
  c3/experiment.py
  c3/generator/devices.py
  c3/libraries/envelopes.py
  c3/main.py
  c3/optimizers/optimalcontrol.py
  c3/optimizers/optimizer.py
  c3/parametermap.py
  c3/signal/gates.py
  c3/utils/log_reader.py
  test/test_envelopes.py
Labels: size/L

#136 Added n_eval
  CHANGELOG.md
  c3/libraries/fidelities.py
  test/test_fidelities.py
Labels: size/M

#144 Reshaping the experiment and model classes for handling different propagation methods
  c3/experiment.py
  c3/libraries/algorithms.py
  c3/libraries/chip.py
  c3/libraries/fidelities.py
  c3/libraries/propagation.py
  c3/main.py
  c3/model.py
  test/c1.cfg
  test/test_optim_init.py
  test/test_transmon_expanded.py
  test/test_two_qubits.py
Labels: size/XL

#129 Update format of the generator chain
  CHANGELOG.md
  c3/generator/generator.py
  docs/Simulated_Model_Learning.rst
  docs/two_qubits.rst
  examples/Simulated_Model_Learning.ipynb
  examples/blackbox_exp.py
  examples/generator.cfg
  examples/single_qubit_blackbox_exp.py
  examples/two_qubit_entangling_gate.ipynb
  examples/two_qubits.ipynb
  test/c2_blackbox_exp.hjson
  test/generator.cfg
  test/generator2.cfg
  test/one_qubit.hjson
  test/test_awg.py
  test/test_generator.py
  test/test_noise.py
  test/test_transmon_expanded.py
  test/test_tunable_coupler.py
  test/test_two_qubits.py
Labels: size/XL

#165 Physics simulation for Qiskit circuits
  .pre-commit-config.yaml
  CHANGELOG.md
  c3/experiment.py
  c3/libraries/propagation.py
  c3/qiskit/c3_backend.py
  examples/c3_qiskit.ipynb
  examples/generator.cfg
  examples/qiskit.cfg
  examples/test_model.cfg
  test/conftest.py
  test/qiskit.cfg
  test/test_model.cfg
  test/test_parsers.py
  test/test_qiskit.py
Labels: enhancement, size/XL
