Repository q-optimize/c3, pull requests merged in 2022-05, with the labels that each got.

#194 Set pulse parameters through Qiskit
  .github/workflows/build_package.yml
  c3/qiskit/c3_backend.py
  c3/qiskit/c3_options.py
  test/test_qiskit.py
Labels: enhancement, size/L

#196 Full Loop with Qiskit
  .gitignore
  examples/Full_loop_single_qubit.ipynb
Labels: documentation, size/XXL

#204 Drop ubuntu 18.04, move to latest
  .github/workflows/build_package.yml
  .github/workflows/nightly_pypi.yml
  .github/workflows/publish_pypi.yml
Labels: size/XS

#202 Refactor signal generation
  c3/c3objs.py
  c3/generator/devices.py
  c3/libraries/envelopes.py
  c3/optimizers/optimizer.py
  c3/signal/gates.py
  c3/signal/pulse.py
  c3/utils/tf_utils.py
  examples/Full_loop_single_qubit.ipynb
  examples/Piecewise_constant_controls.ipynb
  examples/Simulated_Model_Learning.ipynb
  examples/Simulated_calibration.ipynb
  examples/c3_qiskit.ipynb
  examples/generator.cfg
  examples/instructions.cfg
  examples/single_qubit_blackbox_exp.py
  examples/single_qubit_experiment.py
  examples/two_qubit_entangling_gate.ipynb
  examples/two_qubits.ipynb
  test/c2_blackbox_exp.hjson
  test/generator.cfg
  test/generator2.cfg
  test/noise_exp_1.hjson
  test/noise_exp_2.hjson
  test/one_qubit.hjson
  test/test_instruction.py
  test/test_pwc.py
  test/test_two_qubits.py
Labels: size/XXL

#208 Update Parameters through Gate in Qiskit interface
  c3/qiskit/c3_backend.py
  c3/qiskit/c3_gates.py
  test/test_qiskit.py
Labels: enhancement, size/M

#197 Increase evaluation number in OptimalControl
  c3/optimizers/optimalcontrol.py
  test/test_two_qubits.py
Labels: size/XS

#209 Faster legacy response function
  c3/generator/devices.py
  c3/utils/tf_utils.py
  test/c2_blackbox_exp.hjson
  test/one_qubit.hjson
  test/test_generator.py
  test/test_quick_setup.py
  test/test_tf_utils.pickle
  test/test_tf_utils.py
  test/test_transmon_expanded.py
  test/test_tunable_coupler.py
Labels: size/L
